name: Bug
description: バグを登録する場合はこちら
title: "Bug:バグタイトル"
labels: ["bug"]
assignees: [""]
projects: [""]
body:
  - type: markdown
    attributes:
      value: |
        - 必ずMilestoneを設定してください
        - Labelsに"WBS"を設定するとガントチャート表示対象になります
  - type: textarea
    attributes:
      label: 内容を記載
      value: "## 事象

<!-- バグの内容（事象）の説明 -->

<!-- 可能であれば事象のスクリーンショット -->



## 摘出試験項目

<!-- 試験項目番号を列記、なしの場合は、どの契機で摘出したか記載 -->



## 再現方法

<!-- 現象の再現方法を記載する -->

1. ～～を行う

2. ～～

3. ～～



## 環境条件

<!-- 現象発生の条件を記載する、OS,ブラウザのバージョン情報等 -->


## 解析結果

<!-- バグ発生理由が判明している場合は記載 -->


## 対処方法

<!-- バグへの対処方法が判明している場合は記載 -->


## 混入原因

<!-- バグが混入した原因を記載 -->


## 水平展開および結果

<!-- 解析結果、混入原因を踏まえ、水平展開の方法を定義し、その結果を記載 -->


## 再試験項目・結果

<!-- 摘出試験項目、および、追加の試験項目番号を記載し、結果を記載 -->


## 関連事項

<!-- 関連する情報がある場合は記載、水平展開で発見されたバグへのリンク、 -->

"
