name: Minutes
description: 議事録を作成する場合はこちら
title: "内部/外部定例(MM/DD)"
labels: ['議事録']
assignees: [""]
projects: [""]
body:
  - type: textarea
    attributes:
      label: 内容を記載
      value: "# 会議名


外部定例


## 日時


MM/DD (水) 13:00-14:00


## 参加者

* A
* B


## アジェンダ


* 1.前回の打ち合わせメモ

* 2.課題

* 3.今後の進め方


## 次回


MM/DD (水) 13:00-14:00



## 決定事項

* ○○○とする。



## 宿題・課題



NTT東:

* ○○○を提供する(~MM/DD)



AT:

* ○○○を修正する(~MM/DD)

"
